default:
  adapter: postgresql
  encoding: utf8
  host: localhost
  password: "<%= ENV["POSTGRES_DB_DB_PASSWORD"] %>"
  username: "<%= ENV["POSTGRES_DB_USERNAME"] %>"
  pool: 5
development:
  adapter: postgresql
  database: my-send_development
  encoding: utf8
  host: localhost
  password: "<%= ENV["POSTGRES_DB_DB_PASSWORD"] %>"
  username: "<%= ENV["POSTGRES_DB_USERNAME"] %>"
  pool: 5
production:
  adapter: postgresql
  database: my-send_production
  encoding: utf8
  password: "<%= ENV["POSTGRES_DB_DB_PASSWORD"] %>"
  username: "<%= ENV["POSTGRES_DB_USERNAME"] %>"
  host: localhost
test:
  adapter: postgresql
  database: my-send_test
  encoding: utf8
  host: localhost
  password: "<%= Figaro.env.POSTGRES_DB_PASSWORD %>"
  username: "<%= Figaro.env.POSTGRES_DB_USERNAME %>"
  pool: 5
